version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "5050:80"